-- Supabase Schema for Agri-Price Intelligence

-- 1. Table: MSP Rates (Government Data)
CREATE TABLE IF NOT EXISTS msp_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    msp_price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table: Market Prices (Historical Data for ML)
-- In Hybrid mode, this is often loaded from CSV, but good to have a table structure.
CREATE TABLE IF NOT EXISTS market_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    mandi VARCHAR(255) NOT NULL,
    crop VARCHAR(255) NOT NULL,
    modal_price DECIMAL(10, 2) NOT NULL,
    arrival_volume DECIMAL(10, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table: Users (If Auth is used)
-- Managed by Supabase Auth (auth.users), but we can add a profile table.
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID REFERENCES auth.users NOT NULL,
    preferred_mandi VARCHAR(255),
    preferred_crop VARCHAR(255),
    PRIMARY KEY (id)
);

-- Seed Data (Example for Demo)
INSERT INTO msp_rates (crop, year, msp_price) VALUES
('Paddy', 2025, 2400.00),
('Wheat', 2025, 2275.00),
('Turmeric', 2025, 7000.00),
('Coconut', 2025, 3200.00),
('Banana', 2025, 1400.00);
